layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
        #     - bikalims/bika.lims
        #     - bikalims/bika.openhim

social_media:
   linkedin: inusscheepers


topics:
  - name: Indico Plugins
    web_url: https://github.com/indico/indico-plugins

  - name: Bika Labs
    web_url: https://github.com/bikalabs
    image_url: https://avatars3.githubusercontent.com/u/1191551?s=200&v=4

  - name: Bika LIMS
    web_url: https://github.com/bikalims/bika.lims
    image_url: https://avatars3.githubusercontent.com/u/30825552?s=200&v=4

  - name: Bika OpenHIM
    web_url: https://github.com/bikalims/bika.openhim

  - name: Senaite LIMS
    web_url: https://github.com/senaite/senaite.lims
    image_url: https://avatars1.githubusercontent.com/u/29165573?s=200&v=4

  - name: django
    web_url: https://github.com/django
    image_url: https://avatars3.githubusercontent.com/u/27804?s=200&v=4

  - name: freebsd
    web_url: https://freebsd.org

    #  - name: MicroChip
    #web_url: https://github.com/MicrochipTech
    #image_url: https://avatars0.githubusercontent.com/u/8910143?s=200&v=4


